In [101]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [102]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [103]:
a1 = a.reshape(2,6)
a2 = a.reshape(3,4)
a3 = a.reshape(4,3)
a4 = a.reshape(6,2)

#Тут фантазии конец
a5 =  a.reshape(12,1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [104]:
a1 = a.reshape(-1,6)
a2 = a.reshape(-1,4)
a3 = a.reshape(-1,3)
a4 = a.reshape(6,-1)

#Тут фантазии конец
a5 =  a.reshape(12,-1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

**Я думал да, но судя по предыдущим действиям - нет**

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [105]:
c = np.random.randn(3, 4)
c

array([[ 0.87542315,  0.17431363, -0.19981454,  0.44870194],
       [-0.51856261, -1.60410844,  0.74957461,  0.03773796],
       [-0.31387338,  0.60698218,  0.25276013,  0.73637464]])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [106]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [107]:
b = np.arange(20, 0, -2).reshape(-1,1)
print(b)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [108]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c)
c.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [109]:
a = np.arange(12)
print(a)
print('----------------------')

A = a.reshape(4,3)
print(A)
print('----------------------')

At = A.transpose()
print(At)
print('----------------------')

B = np.dot(A,At)
print(B)
print('----------------------')

print(B.shape)
print('----------------------')

d = np.linalg.det(B)
print(d)
#Определитель 0 - обратной матрицы не существует


[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------------
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
----------------------
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
----------------------
(4, 4)
----------------------
0.0


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [110]:
np.random.seed(43)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [111]:
c = np.random.randint(0, 16,16)
c

array([ 4,  0, 15,  1,  5, 10,  0,  3,  1, 11, 11,  2, 14, 14,  7,  0])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [112]:
C = c.reshape(4,4)
print(C)
print('----------------------')

D = B + C*10
print(D)
print('----------------------')

print(np.linalg.det(D))
print('----------------------')

print(np.linalg.matrix_rank(D))
print('----------------------')

D_inv = np.linalg.inv(D)
print(D_inv)


[[ 4  0 15  1]
 [ 5 10  0  3]
 [ 1 11 11  2]
 [14 14  7  0]]
----------------------
[[ 45  14 173  42]
 [ 64 150  86 152]
 [ 33 196 259 232]
 [172 262 282 302]]
----------------------
36392399.99999995
----------------------
4
----------------------
[[ 0.00392774  0.00203559 -0.00971576  0.00589299]
 [ 0.05394808  0.11746519 -0.01527187 -0.05489223]
 [ 0.01590387  0.01937987 -0.00103043 -0.01117431]
 [-0.06389026 -0.12116266  0.01974478  0.05801101]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [113]:
np.place(D_inv,D_inv<0,0)
np.place(D_inv,D_inv>0,1)
print(D_inv)

E = np.where (D_inv,B,C)


[[1. 1. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]]


In [114]:
print(E)

[[  5  14  15  32]
 [ 14  50   0   3]
 [ 23  86  11   2]
 [ 14  14 212 302]]
